export const UserInterfaceActionTypes = {
  TOGGLE_UPDATE_PROFILE_PHOTO: 'TOGGLE_UPDATE_PROFILE_PHOTO',
  TOGGLE_HEADER_DROPDOWN_SETTINGS: 'TOGGLE_HEADER_DROPDOWN_SETTINGS',
  TOGGLE_FEELING_ACTIVITY: 'TOGGLE_FEELING_ACTIVITY',
  TOGGLE_NOTIFICATIONS: 'TOGGLE_NOTIFICATIONS',
};
